flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- esqueleto-2.4.3
- hledger-web-1.0.1
- persistent-2.2.4.1
- persistent-sqlite-2.2.1
- persistent-template-2.1.8.1
- unix-time-0.3.6
- wai-handler-launch-3.0.2.1
resolver: lts-7.7
